/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "umztyflxebzhqlfnmwwb";
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVtenR5Zmx4ZWJ6aHFsZm5td3diIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjI1MTU4ODksImV4cCI6MjA3ODA5MTg4OX0.HSW_k49rXT8HaRiJmwG_b6e7e3wkwVbDJwD2uV7HN-Y";
